In [ ]:
#Q1
Name = "Srija ch"
Age = "20"
print(Name)
print(Age)

Srija ch
20


In [ ]:
#Q2

x = "Datascience is used to extract meaningful insights."
print(x.split())

['Datascience', 'is', 'used', 'to', 'extract', 'meaningful', 'insights.']


In [ ]:
#Q3

def multiplication(n1,n2):
  product = n1*n2
  return product
res=multiplication(18,30)
print(res)

540


In [ ]:
#Q4

Dictionary = {'Andhra Pradesh' : 'Amaravati', 'Assam' : 'Dispur', 'Maharashtra':'Mumbai',
 'Bihar':'Patna','Goa':'Panaji'}
print(Dictionary)
print(Dictionary.keys())
print(Dictionary.values())

{'Andhra Pradesh': 'Amaravati', 'Assam': 'Dispur', 'Maharashtra': 'Mumbai', 'Bihar': 'Patna', 'Goa': 'Panaji'}
dict_keys(['Andhra Pradesh', 'Assam', 'Maharashtra', 'Bihar', 'Goa'])
dict_values(['Amaravati', 'Dispur', 'Mumbai', 'Patna', 'Panaji'])


In [ ]:
#Q5
def createList(n1, n2):
 return list(range(n1, n2+1))
n1, n2=1, 1000
print(createList(1,1000))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 22

In [ ]:
#Q6
import numpy as np
dim = 4
identity_matrix=np.identity(dim, dtype="int")
print(identity_matrix)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [ ]:
#Q7
import numpy as np
x=np.arange(1,10).reshape(3,3)
print(x)#Q8
import numpy as np
arr1=[1, 3, 4, 5]
arr2=[6, 7, 8, 9]
sum = np.add(arr1, arr2)
print(sum)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 7 10 12 14]


In [ ]:
#Q8
import numpy as np
arr1=[1, 3, 4, 5]
arr2=[6, 7, 8, 9]
sum = np.add(arr1, arr2)
print(sum)

[ 7 10 12 14]


In [ ]:
#Q9
from datetime import datetime
import pandas as pd
start_date=datetime.strptime("2023-02-01", "%Y-%m-%d")
end_date=datetime.strptime("2023-03-01", "%Y-%m-%d")
D='D'
date_list = pd.date_range(start_date, end_date, freq=D)
print(f"Creating list of dates starting from{start_date} to {end_date}")
print(date_list)

Creating list of dates starting from2023-02-01 00:00:00 to 2023-03-01 00:00:00
DatetimeIndex(['2023-02-01', '2023-02-02', '2023-02-03', '2023-02-04',
               '2023-02-05', '2023-02-06', '2023-02-07', '2023-02-08',
               '2023-02-09', '2023-02-10', '2023-02-11', '2023-02-12',
               '2023-02-13', '2023-02-14', '2023-02-15', '2023-02-16',
               '2023-02-17', '2023-02-18', '2023-02-19', '2023-02-20',
               '2023-02-21', '2023-02-22', '2023-02-23', '2023-02-24',
               '2023-02-25', '2023-02-26', '2023-02-27', '2023-02-28',
               '2023-03-01'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
#Q10
import pandas as pd
data={'Brand' : ['Maruti', 'Renault', 'Hyndai'], 'Sales' : ['250', '200', '240']}
dataframe = pd.DataFrame.from_dict(data)
print(dataframe)

     Brand Sales
0   Maruti   250
1  Renault   200
2   Hyndai   240
